### ISSUE TITLE
Explicit result of sending message.

### ISSUE THREAD

**Issue by ukint-vs** [gear-tech/gear#277] opened 2021-09-21 17:40 UTC
### Problem to Solve

If we send a message to a non-existent ID, it will be removed from the message queue, but on the contract side, this can't be found out. 

### Possible Solution

Return `Result<MessageId, &str>` from send syscall.

**Comment by breathx** [comment] 2021-11-12 04:02
Should be closed as duplicate of #314 ?

@shamilsan @ukint-vs

**Closed** 2021-11-12 10:12 UTC
Labels: D1-core, D3-gstd, C1-feature
