### ISSUE TITLE
Create program from program

### ISSUE THREAD

**Issue by NikVolf** [gear-tech/gear#245] opened 2021-09-15 08:54 UTC

**Comment by NikVolf** [comment] 2021-11-15 16:40
This also should be totally asynchronous, and priced on host side

**Comment by SabaunT** [comment] 2021-11-30 11:43
I decided to write down some thoughts on that in order to form an implementation plan for this feature. This is needed, because the feature affects and is being affected by different parts and design solutions of the Gear. Consequently, closing the issue can be involved with a number of merge conflicts. Right now @gshep does some stuff close to the issue.

While the process is totally asynchronous, we have can have 2 different API types for program creation from program: the blocking one (just add a new message to the storage queue) and non-blocking, i.e. `async` one (wait for the result of a new program creation).

To me from user space it looks like the following. From *init* and *handle*/*handle_reply* functions we could do like this in **blocking style**:
```rust
// this creates a new init message to be processed by runner
let new_prog: ProgramId = msg::create_program(some_data_for_init_msg);
// this creates a new dispatch message, that will be handled in `handle` function of the new program.
// Note: this is creates a message to not yet initialized program.
msg::send(new_prog, payload, gas_limit, value);
```
**And in async style**:
```rust
let new_prog: Result<ProgramId, _> = msg::create_program_and_wait(some_data_for_init_msg).await;
if let Ok(prog_id) = new_prog {
    msg::send(prog_id, payload, gas_limit, value);
}
```

So the **FIRST** solution for the issue is to **first** create a blocking API, rather then an async, because, without having done an _async init_ it's wrong to start with async program creating API. What's more @gshep is now working on #232 (along with #18, which is an important part for the async progam creation). So for the sake of not doing the same job twice and also bearing in mind the fact, that the colleague has already some design on that, I decided to focus on blocking API.

The **SECOND** solution for the issue is to follow the iterative implementation plan. The rationale for the iteration plan is to not to make a huge PR with lots of changes, which will be hard to review and hard to find possible cons and warnings. Instead, I offer a sequence of iterations each of which has a known set of limitations, indicated later.

**ITERATION 1**
1. Create `submit_code` #347, which saves the provided code in the state and returns the code hash later used in program creation. No code should be added to the storage if code already exists.
2. Create a sys-call `create_program` (can be `new_program` and etc., the name is to be discussed):
    - User provides to the function 1) the code hash which he got after `submit_code`, 2) some salt (salt management is a user space task), 3) payload data, 4) gas limit, 5) value.
    - The sys-call returns a  new program id computed from salt and code hash. The logic of program id creation should be changed from `prog_id = h(code + salt)` to `prog_id = h(code_hash + salt)`.
    - The sys-call creates a message that later is processed by the node. Details on this will follow. 
3. Some details on internal changes in `core` and `core_runner`. When a new message is sent from the program by using `msg::send` we first create an `OutgoingPacket`, which is almost the same as the `OutgoingMessage`, except for not having a message id, therefore being a kind of interim object, designating not fully formed message. Later the `OutgoingMessage` is transformed to `core::Message` in runner and so on. Current design is all about "dispatching" messages, but not "ready" for  "outgoing init request" messages. We have here three possible solutions. Let's decide on them.
    a. IMHO, the rightest solution is to use enums instead of structs for outgoing packets/messages and `core::Message` (the latter is done by @gshep in issues that he self-assigned). But it will end-up in lots of consequent changes (using `match` stuff everywhere). I suggest postponing that, because <...>
    b. The fast solution can be defining the reserved destination address, when deploying a program from program. Pros: 1) do not touch outgoing packet/message and `core::Mesage`, 2) data type is not changed in the message queue (storage) and 3) by checking for the reserved address we can later separate in node queue processing logic the initialization messages and the dispatch messages. Cons: need to check that user didn't provide DEPLOY_DESTINATION as a destination for the sending message. Another variation here can be making the destination field type to be `Option`, but it can have same consequences as the "rightest" solution (using `if let Some` every time we use refer to message destination).
    c. Create a new message type like `OutgoingInitMessage` and 1) return the vector of such messages separately in `ExecutionReport` (so, their type is separate from `core::Messages` and such messages will have own prefix in storage queue)  or 2) convert it to the variation of `core::Message` (so the `core::Message` is an enum).
4. Regardless of the upper choice, we will still process such init messages in `process_queue`'s [loop](https://github.com/gear-tech/gear/blob/master/pallets/gear/src/lib.rs#L498). Basing on message type (if solution is chosen **a** or **c** in the last step) or message destination (if solution **b** is chosen), `process` or `init_program` of `node_runner` will be run.
5. An important thing to mention is message ordering. As far as I understand, _there are no requirements for messages order_ (correct me if I'm wrong) if multiple messages are sent from one program function (i.e., multiple outgoing messages created after running the one). Although they are put to FIFO queue, there are no guarantees in message processing order. However, if we first process the handle message for a program created from program, before processing init message, the handle message will go to log. Therefore we should guarantee that init message created after `msg::create_program` syscall will be processed before messages sent to the new, not yet initialized program. Currently, this can be done by prioritizing init messages processing in the [loop](https://github.com/gear-tech/gear/blob/master/pallets/gear/src/lib.rs#L498). With the current logic it will work like this: we try to process init messages and if the gas allowance of the block isn't enough for any of it, we [break](https://github.com/gear-tech/gear/blob/master/pallets/gear/src/lib.rs#L500-L503) from the loop. 

What are main problems of the **ITERATION 1**:
1. If parent program ended with a trap, but child program creation messages were sent and successfully processed, we can face situations, when successfully created child send message to it's failed during initialization parent. Yeah, such messages will go to log (because there isn't such destination program id), but these messages weren't intended to be added to the log.
2. Current message processing doesn't utilize block gas allowance. There are possible situations when someone created an `OutgoingMessage` (from program) with a very big gas limit greater than block gas allowance. This will end up in a situation when we do an "early break" from the processing loop, if actual gas needed to process the message with a great gas limit was less then block gas allowance. Therefore we should not stick to that "break" for guaranteeing the order of processing. 
Some proposals to make the process of a new contract creation more convenient:
1. We can do `submit_code` only for one code. Could be better to make the extrinsic accept a packet of program codes. 
2. Users can make mistakes in managing salt. For example, for salt user can use in his factory contract some incrementor. But if someone else deploys the same factory, all the `create_program` calls will fail, because the code_hash and salt (provided with an incrementor) values will be used again. We can provide users with some `CodeDeployManager` from `gstd`, which will manage the salt and other stuff and etc.

**ITERATION 2**:
1. Handle program exit with a trap: if trap happened, do not propagate changes, stored in `Ext` (i.e. `MessageContext`, `MemoryContext` and so on). This is intended to solve the first problem.
2. In order not to solve the second problem we can add handle messages for an uninitialized yet program (the one, for which the init message wasn't processed yet) the following way: the current code will add messages for non-existent destination to the log, but messages intended for a log differ from the handle ones being sent to uninitialized program in the way, that the latter is sent to some entity, which _already have an associated code_. So, in runner after checking message destination for existence in program storage we can check whether it has an associated code with it. For that we should have a map in storage which creates a relation between program id and code hash (32 bytes to 32 bytes). For storing such values we can charge some constant gas amount. 
3. Solve the two proposals, stated earlier.

**Comment by jss180827** [comment] 2022-01-13 12:00
大神啊

**Closed** 2022-02-24 11:38 UTC
Labels: D1-core, P1-asap
