### ISSUE TITLE
I can not get the panic message in a contract test using gtest

### ISSUE THREAD

**Issue by kaiweicai** [gear-tech/gear#3518] opened 2023-11-22 16:30 UTC
### Problem

When doing a failed test,the contract prints this sten

### Steps

1.
2.
3.

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

**Comment by shamilsan** [comment] 2023-11-22 18:12
Closing as a duplicate of #3520

**Closed by shamilsan** 2023-11-22 18:12 UTC
