### ISSUE TITLE
Ability to resume stopped programs

### ISSUE THREAD

**Issue by gshep** [gear-tech/gear#2564] opened 2023-04-19 05:54 UTC
### Problem to Solve

#2301  introduces pausing programs mechanism, #2509 adds ability to extend rent period. The intention of this task is to add extrinsic `resume_program` to provide ability to users to run programs again.

### Possible Solution

-
after #2509

**Comment by shamilsan** [comment] 2023-06-25 08:49
Closing as a duplicate of #2605

**Closed by shamilsan** 2023-06-25 08:49 UTC
Labels: D2-node, C1-feature
