### ISSUE TITLE
Re-use memory instances in gear_sandbox

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#2936] opened 2023-07-12 17:47 UTC
### Problem to Solve

Currently we need to make a new memory for each new program execution. Even more we need to pay twice for page, which has been already loaded during last execution. 

### Possible Solution

To solve this problem we can leave memory instance after successful execution. Lazy-pages context for this memory must stay the same, in order to be able to charge only for pages that has not been already accessed.
More clear explanation:
1) After first successful execution of the program in block, we remain memory and lazy-pages state.
2) For each next execution we use a copy of that memory and lazy-pages state until some execution does not become successful.
3) Then we replace saved memory instance with new one and the same for lazy-pages state.
4) Continue until the end of the block the same logic.
5) In the end or in the begging of the process queue we must drop saved memories and lazy-pages states.

This solution of cause have some weaknesses, like - how expensive copying of full memory instance can be ? May be better to drop memory instance after first not successful execution, which has made at least one write to memory.

**Comment by gshep** [comment] 2023-09-12 08:00
duplicate of #1858

**Closed by gshep** 2023-09-12 08:00 UTC
Labels: C1-feature
