### ISSUE TITLE
Write tests for `send_from_reservation` precise syscall in `wasm-gen`

### ISSUE THREAD

**Issue by mertwole** [gear-tech/gear#3172] opened 2023-08-24 14:23 UTC
### Problem to Solve

#3171

### Possible Solution

Test anywhere in `wasm-gen` that `precise_send_from_reservation` works correctly

**Comment by StackOverflowExcept1on** [comment] 2023-09-20 08:39
duplicate of #3171?

**Closed by StackOverflowExcept1on** 2023-09-20 08:39 UTC
Labels: C2-refactoring, D4-test, D5-tooling
